version: '3'

services:
  app:
    build:
      context: './app'
      dockerfile: Dockerfile
    links:
      - redis
    ports:
      - "9000"
    volumes:
      - ./app/:/usr/local/docker/app
    environment:
      - REDIS_SCHEME=tcp
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    links:
      - app
    ports:
      - 8080:80
    volumes:
      - ./docker/var/log/nginx:/var/log/nginx

  redis:
    image: "redis:latest"
    ports:
      - "6379"
    volumes:
      - "./docker/redis/data:/data"